name: game_on
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.7.3
  flame_forge2d: ^0.13.0+1
  another_flushbar: ^1.12.30
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  shared_preferences:
  provider: ^6.1.1
  fluttertoast: ^8.2.4
  dio: ^5.4.0
  flutter_widget_from_html:
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  url_launcher:
  webview_flutter: 3.0.4
  image_picker: ^1.1.2
  just_audio: ^0.9.36
  audioplayers:
  animated_text_kit: ^4.2.1
  dotted_border: ^2.1.0
  connectivity_plus: ^5.0.2
  url_strategy: ^0.2.0
  share_plus: ^7.2.2
  http:
  flutter_tts: ^4.2.2
  socket_io_client: ^2.0.3+1
  draggable_fab: ^0.1.4
  add_to_cart_animation: ^2.0.3
  google_fonts: ^6.2.1
  flutter_inappwebview:
  page_transition: ^2.1.0
  flutter_flip_card:
  fwfh_text_style: ^2.23.8
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assetss/images/
    - assetss/images/coin/
    - assetss/images/robot/
    - assetss/images/explosion/
    - assetss/
    - assets/
    - assets/icons/
    - assets/music/
    - assets/images/
    - assets/person/
    - assets/category/
    - assets/aviator/
    - assets/chips/
    - assets/cards/
    - assets/dragontiger/
    - assets/win_go/
    - assets/mines/
    - assets/trx/
    - assets/titli/
    - assets/Andarbahar/
    - assets/HeadTail/
    - assets/lucky_12/
    - assets/lucky_16/
    - assets/triple_chance/
    - assets/jackpot/
    - assets/spin/
    - assets/fun_target/
    - assets/teen_patti/
    - assets/teen_patti/cards/
    - assets/teen_patti/cards/clubs/
    - assets/teen_patti/cards/hearts/
    - assets/teen_patti/cards/spades/
    - assets/teen_patti/cards/diamonds/
    - assets/teen_patti/person/
    - assets/teen_patti/sound_effects/
    - assets/seven_up_down_new/
    - assets/seven_up_down_new/loading7.gif



