// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnDCJhCajRdpPH-nkim_eoDgv7YckT6lw',
    appId: '1:663442341318:web:55a827e625067a9a3586c7',
    messagingSenderId: '663442341318',
    projectId: 'gameon-c83d1',
    authDomain: 'gameon-c83d1.firebaseapp.com',
    storageBucket: 'gameon-c83d1.firebasestorage.app',
    measurementId: 'G-XTJFD2CX21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEUn15yyPiSUZkZaONr8bq-91B0v74z5k',
    appId: '1:663442341318:android:2de44906f4ad486a3586c7',
    messagingSenderId: '663442341318',
    projectId: 'gameon-c83d1',
    storageBucket: 'gameon-c83d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMC6fbm_j8oqRznGv5IPwAVqmwmcAPn8c',
    appId: '1:663442341318:ios:96950b77c41bd7973586c7',
    messagingSenderId: '663442341318',
    projectId: 'gameon-c83d1',
    storageBucket: 'gameon-c83d1.firebasestorage.app',
    iosBundleId: 'com.treamz.plinko.flutterPlinko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMC6fbm_j8oqRznGv5IPwAVqmwmcAPn8c',
    appId: '1:663442341318:ios:96950b77c41bd7973586c7',
    messagingSenderId: '663442341318',
    projectId: 'gameon-c83d1',
    storageBucket: 'gameon-c83d1.firebasestorage.app',
    iosBundleId: 'com.treamz.plinko.flutterPlinko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnDCJhCajRdpPH-nkim_eoDgv7YckT6lw',
    appId: '1:663442341318:web:3ff5ba0a751333223586c7',
    messagingSenderId: '663442341318',
    projectId: 'gameon-c83d1',
    authDomain: 'gameon-c83d1.firebaseapp.com',
    storageBucket: 'gameon-c83d1.firebasestorage.app',
    measurementId: 'G-5XBN38Y3HC',
  );
}
